Revert "sacus.dispatcher: cleaned WSGIMapper.__call__()"
Module sancus.dispatcher:19 in __call__
>>  factory, handler, kw = self.find_handler(environ)
TypeError: 'NoneType' object is not iterable

This reverts commit 8bf2a3898af99e9de4adf80d2c4b01bc026b928b.